### ISSUE TITLE
Mudança nos parametros de estorno

### ISSUE THREAD

**Issue by guilhermebruzzi** [Cappta/android-applink-samples#4]
ex.: Cappta://payment-reversal/?parametrosIda&scheme=instore

Mudar a action e garantir que a resposta também mande a mesma action de payment-reversal.

- paymentId: string (deve retornar esse mesmo paymentId na volta)
- administrativeCode: string (e.g. Cappta para cancelar)
- authKey: string (e.g. "<cappta_authKey>"),
- administrativePassword: [string] (e.g. Senha da Cappta para cancelar) <- verificar se pode retirar do fluxo

**Comment by rmterra** [comment]
Opa, implementado já tem algum tempinho hehe
